version: "3"
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: "mariadb"
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/var/lib/mysql

  # If not required comment it out
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    restart: unless-stopped
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80